### ISSUE TITLE
NullReferenceException with Bearer Token (No Roles Claims)

### ISSUE THREAD

**Issue by WorldMaker** [kirkone/KK.AspNetCore.EasyAuthAuthentication#52]
I'm seeing a NullReferenceException attempting to use Bearer Tokens (`/auth/me` `$[0].access_token`):

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at KK.AspNetCore.EasyAuthAuthentication.Services.EasyAuthForAuthorizationTokenService.BuildFromAuthToken(JObject xMsClientPrincipal, ProviderOptions options)
   at KK.AspNetCore.EasyAuthAuthentication.Services.EasyAuthForAuthorizationTokenService.AuthUser(HttpContext context, ProviderOptions options)
   at KK.AspNetCore.EasyAuthAuthentication.EasyAuthAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

I'm not seeing a similar error for other Authentication methods (`X-` headers or no headers when local). My current AAD setup, for whatever reason, is not returning any Roles claims and it looks like this is the only provider path with separate Role Claim ingestion.

**Comment by paule96** [comment]
you can find it [here](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=package&feed=KK.AspNetCore.EasyAuthAuthentication%40Local&package=KK.AspNetCore.EasyAuthAuthentication&protocolType=NuGet&version=2.0.3-pre-2021402&view=overview).


The version of nuget will take two or three days more.

**Comment by paule96** [comment]
[Released](https://www.nuget.org/packages/KK.AspNetCore.EasyAuthAuthentication/)
